use crate::graph::{ShaderDef, TensorMode};
pub mod shaders;

pub fn load_core_shaders() -> Vec<ShaderDef> {
    vec![
        // FWD
        ShaderDef::new(
            "MatMul",
            include_str!("../shaders/fwd/matmul.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "MatMulTrp",
            include_str!("../shaders/fwd/matmul_trp.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "Embedding",
            include_str!("../shaders/fwd/embedding.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "RMSNorm",
            include_str!("../shaders/fwd/rmsnorm.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "SiLU",
            include_str!("../shaders/fwd/silu.wgsl"),
            vec![TensorMode::InOut],
        ),
        ShaderDef::new(
            "RoPE",
            include_str!("../shaders/fwd/rope.wgsl"),
            vec![TensorMode::InOut, TensorMode::Meta],
        ),
        ShaderDef::new(
            "Softmax",
            include_str!("../shaders/fwd/softmax.wgsl"),
            vec![TensorMode::InOut, TensorMode::Meta],
        ),
        ShaderDef::new(
            "CrossEntropy",
            include_str!("../shaders/fwd/cross_entropy.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Output,
                TensorMode::Output,
                TensorMode::Meta,
            ],
        ),
        // BWD
        ShaderDef::new(
            "RMSNormBwd",
            include_str!("../shaders/bwd/rmsnorm_bwd.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "RMSNormWeightBwd",
            include_str!("../shaders/bwd/rmsnorm_weight_bwd.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Output,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "SiLUBwd",
            include_str!("../shaders/bwd/silu_bwd.wgsl"),
            vec![TensorMode::InOut],
        ),
        ShaderDef::new(
            "RoPEBwd",
            include_str!("../shaders/bwd/rope_bwd.wgsl"),
            vec![TensorMode::InOut, TensorMode::Meta],
        ),
        ShaderDef::new(
            "SoftmaxBwd",
            include_str!("../shaders/bwd/softmax_bwd.wgsl"),
            vec![TensorMode::InOut, TensorMode::Meta],
        ),
        ShaderDef::new(
            "MatMulWeightBwd",
            include_str!("../shaders/bwd/matmul_weight_trp.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "EmbeddingBwd",
            include_str!("../shaders/bwd/embedding_bwd.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Output,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "CrossEntropyBwd",
            include_str!("../shaders/bwd/cross_entropy_bwd.wgsl"),
            vec![
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Input,
                TensorMode::Output,
                TensorMode::Meta,
            ],
        ),
        ShaderDef::new(
            "AdamW",
            include_str!("../shaders/bwd/adamw.wgsl"),
            vec![
                TensorMode::InOut,
                TensorMode::Input,
                TensorMode::InOut,
                TensorMode::InOut,
                TensorMode::Meta,
                TensorMode::Meta,
            ],
        ),
    ]
}
